In [1]:
import pandas as pd

In [2]:
import numpy as np

In [3]:
file = pd.read_csv('Pset1.csv')

In [19]:
print(file.shape)
print(file.columns)
print(file.head())

(161493, 43)
Index(['rectype', 'pldel3', 'birattnd', 'cntocpop', 'stresfip', 'dmage',
       'ormoth', 'mrace3', 'dmeduc', 'dmar', 'adequacy', 'nlbnl', 'dlivord',
       'totord9', 'monpre', 'nprevist', 'isllb10', 'dfage', 'orfath', 'dfeduc',
       'birmon', 'weekday', 'dgestat', 'csex', 'dbrwt', 'dplural', 'omaps',
       'fmaps', 'clingest', 'anemia', 'cardiac', 'lung', 'diabetes', 'herpes',
       'chyper', 'phyper', 'pre4000', 'preterm', 'tobacco', 'cigar6',
       'alcohol', 'drink5', 'wgain'],
      dtype='object')
   rectype  pldel3  birattnd  cntocpop  stresfip  dmage  ormoth  mrace3  \
0        1       1       2.0       NaN        42     30     0.0       1
1        1       2       1.0       NaN        42     31     0.0       1
2        1       1       1.0       NaN        42     21     0.0       1
3        2       1       2.0       NaN        24     29     0.0       1
4        1       1       1.0       NaN        42     30     0.0       1

   dmeduc  dmar  ...  herpes  chyper  phyper  pre4000  preterm  tobacco  \
0    10.0     2  ...       2       2       2        2        2        2
1    12.0     1  ...       2       2       2        2        2        2
2    12.0     1  ...       2       2       2        2        2        2
3    12.0     1  ...       2       2       2        2        2        2
4    13.0     1  ...       1       2       2        2        2        2

   cigar6  alcohol  drink5  wgain
0       0        2       0     33
1       0        2       0     16
2       0        2       0     40
3       0        2       0     25
4       0        2       0     36

[5 rows x 43 columns]

In [4]:
print(file['ormoth'].value_counts())

0.0    154987
2.0      4098
5.0       898
4.0       630
1.0       587
3.0        99
Name: ormoth, dtype: int64

In [53]:
lis = ['cardiac', 'lung', 'diabetes', 'herpes',
       'chyper', 'phyper', 'pre4000', 'preterm', 'tobacco', 'cigar6',
       'alcohol', 'drink5', 'wgain']
for item in lis:
    print(file[item].value_counts())

2    160224
1      1186
Name: cardiac, dtype: int64
2    160074
1      1336
9        83
Name: lung, dtype: int64
2    157263
1      4147
9        83
Name: diabetes, dtype: int64
2    160372
1      1032
9        83
8         6
Name: herpes, dtype: int64
2    160102
1      1308
9        83
Name: chyper, dtype: int64
2    156481
1      4929
9        83
Name: phyper, dtype: int64
2    159234
1      2176
9        83
Name: pre4000, dtype: int64
2    158784
1      2626
9        83
Name: preterm, dtype: int64
2    129285
1     31977
9       231
Name: tobacco, dtype: int64
0    129285
2     12920
3      9269
1      6706
6      1924
4      1330
5        59
Name: cigar6, dtype: int64
2    156129
1      5074
9       290
Name: alcohol, dtype: int64
0    156129
5      3286
1       749
2       504
4       489
3       336
Name: drink5, dtype: int64
30    16204
25    10689
20     9178
40     8911
35     8401
      ...
92        3
91        2
94        2
95        2
97        1
Name: wgain, Length: 99, dtype: int64

In [60]:
file['cardiac'] = file['cardiac'].replace({9: None} )
file['lung'] = file['lung'].replace({9: None} )
file['diabetes'] = file['diabetes'].replace({9: None} )
file['herpes'] = file['herpes'].replace({9: None} )
file['herpes'] = file['herpes'].replace({8: None} )
file['chyper'] = file['chyper'].replace({9: None} )
file['phyper'] = file['phyper'].replace({9: None} )
file['pre4000'] = file['pre4000'].replace({9: None} )
file['preterm'] = file['preterm'].replace({9: None} )
file['tobacco'] = file['tobacco'].replace({9: None} )
file['cigar6'] = file['cigar6'].replace({6: None} )
file['alcohol'] = file['alcohol'].replace({9: None})
file['wgain'] = file['wgain'].replace({99:None})
file['drink5'] = file['drink5'].replace({5:None})

In [61]:
lis = ['cardiac', 'lung', 'diabetes', 'herpes',
       'chyper', 'phyper', 'pre4000', 'preterm', 'tobacco', 'cigar6',
       'alcohol', 'drink5', 'wgain']
for item in lis:
    print(file[item].value_counts())

2.0    160224
1.0      1186
Name: cardiac, dtype: int64
2.0    160074
1.0      1336
Name: lung, dtype: int64
2.0    157263
1.0      4147
Name: diabetes, dtype: int64
2.0    160372
1.0      1032
Name: herpes, dtype: int64
2.0    160102
1.0      1308
Name: chyper, dtype: int64
2.0    156481
1.0      4929
Name: phyper, dtype: int64
2.0    159234
1.0      2176
Name: pre4000, dtype: int64
2.0    158784
1.0      2626
Name: preterm, dtype: int64
2.0    129285
1.0     31977
Name: tobacco, dtype: int64
0    129285
2     12920
3      9269
1      6706
4      1330
5        59
Name: cigar6, dtype: int64
2.0    156129
1.0      5074
Name: alcohol, dtype: int64
0    156129
1       749
2       504
4       489
3       336
Name: drink5, dtype: int64
30.0    16204
25.0    10689
20.0     9178
40.0     8911
35.0     8401
        ...
92.0        3
95.0        2
91.0        2
94.0        2
97.0        1
Name: wgain, Length: 98, dtype: int64

In [52]:
print(file['cardiac'].value_counts())
#print(file['cardiac'])
print(file['cntocpop'].value_counts())

2    160224
1      1186
Name: cardiac, dtype: int64
0.0    50052
2.0    43136
3.0    30187
1.0    20666
Name: cntocpop, dtype: int64

In [62]:
for obj in file.columns:
    print(file[obj].value_counts())

1    119821
2     41672
Name: rectype, dtype: int64
1    158285
2      3208
Name: pldel3, dtype: int64
1.0    137000
2.0     16411
3.0      5950
4.0      1182
5.0       949
Name: birattnd, dtype: int64
0.0    50052
2.0    43136
3.0    30187
1.0    20666
Name: cntocpop, dtype: int64
42    157075
34      2277
36       739
39       417
24       358
10       289
54        99
12        40
0         28
51        27
6         23
37        18
13        11
17         8
25         8
21         7
47         7
45         7
9          6
48         6
26         5
53         5
55         4
4          3
8          3
40         3
27         2
29         2
11         2
19         2
23         1
22         1
46         1
32         1
44         1
33         1
41         1
28         1
38         1
1          1
31         1
30         1
Name: stresfip, dtype: int64
29    10307
28    10072
30     9910
27     9764
26     9251
31     9214
25     8834
32     8438
24     8025
22     7959
23     7760
33     7139
21     6937
20     6425
34     6042
19     5743
35     5207
18     4462
36     4075
17     3141
37     3003
38     2193
16     2080
39     1583
40     1082
15     1074
41      647
42      353
14      312
43      207
44       93
13       77
45       43
46       27
47        7
12        4
48        2
49        1
Name: dmage, dtype: int64
0.0    154987
2.0      4098
5.0       898
4.0       630
1.0       587
3.0        99
Name: ormoth, dtype: int64
1    133608
3     24531
2      3354
Name: mrace3, dtype: int64
12.0    66391
16.0    23744
14.0    15574
17.0    11411
13.0    11138
11.0     8692
10.0     7577
15.0     4706
9.0      4670
8.0      3600
7.0       425
6.0       255
5.0        97
0.0        88
4.0        77
3.0        50
2.0        44
1.0        31
Name: dmeduc, dtype: int64
1    109600
2     51893
Name: dmar, dtype: int64
1.0    111560
2.0     34658
3.0     11160
Name: adequacy, dtype: int64
0.0     64785
1.0     53842
2.0     26354
3.0      9751
4.0      3663
5.0      1535
6.0       737
7.0       390
8.0       187
9.0       105
10.0       61
11.0       28
12.0       22
13.0        2
14.0        1
15.0        1
Name: nlbnl, dtype: int64
1.0     64196
2.0     53279
3.0     26512
4.0     10165
5.0      3910
6.0      1660
7.0       818
8.0       416
9.0       229
10.0      121
11.0       65
12.0       40
13.0       24
14.0        6
15.0        1
16.0        1
Name: dlivord, dtype: int64
1.0    49137
2.0    47868
3.0    31074
4.0    16391
5.0     8234
6.0     4247
8.0     2444
7.0     2014
Name: totord9, dtype: int64
2.0    73216
3.0    33249
1.0    21713
4.0    11845
5.0     6833
6.0     4389
7.0     2920
0.0     2307
8.0     1758
9.0      572
Name: monpre, dtype: int64
12.0    26409
10.0    21525
13.0    15839
11.0    14211
14.0    13028
9.0     11474
8.0     10575
15.0     9229
7.0      6904
6.0      5441
5.0      3877
16.0     3722
4.0      2751
0.0      2307
3.0      2145
17.0     1633
2.0      1599
20.0     1578
18.0     1320
1.0      1048
19.0      574
21.0      224
22.0      221
25.0      208
24.0      116
23.0      109
30.0       84
26.0       43
28.0       33
27.0       29
29.0       15
35.0       13
32.0       13
49.0       13
31.0       12
36.0       12
40.0       10
34.0        8
38.0        7
33.0        7
39.0        3
48.0        2
47.0        1
46.0        1
41.0        1
37.0        1
42.0        1
Name: nprevist, dtype: int64
0.0    64196
5.0    22363
6.0    14940
9.0    13291
4.0    12639
3.0     9521
7.0     8765
8.0     5465
2.0     1447
1.0     1363
Name: isllb10, dtype: int64
29.0    9613
30.0    9482
31.0    9168
28.0    9056
32.0    9006
        ...
67.0       3
78.0       1
72.0       1
12.0       1
71.0       1
Name: dfage, Length: 62, dtype: int64
0.0    151361
2.0      4092
5.0       854
1.0       774
4.0       734
3.0       117
Name: orfath, dtype: int64
12.0    69610
16.0    22727
17.0    15196
14.0    12610
13.0     7248
11.0     6820
10.0     5394
15.0     3676
9.0      3019
8.0      3004
7.0       290
6.0       253
4.0       105
5.0        69
0.0        64
2.0        62
3.0        58
1.0        25
Name: dfeduc, dtype: int64
7     14191
8     14083
3     13981
9     13968
5     13928
4     13589
1     13417
6     13314
10    13308
12    12881
2     12422
11    12411
Name: birmon, dtype: int64
6    25518
3    25511
4    25370
5    25136
2    23163
7    19058
1    17737
Name: weekday, dtype: int64
40.0    36984
39.0    35953
41.0    22848
38.0    22181
37.0    10992
42.0     8270
36.0     5831
35.0     3480
43.0     3167
34.0     2266
44.0     1816
33.0     1279
45.0     1086
32.0      952
31.0      657
46.0      574
30.0      556
47.0      405
29.0      385
28.0      325
27.0      246
26.0      209
25.0      187
24.0      155
23.0      128
22.0      128
21.0       83
20.0       63
19.0       45
18.0       35
17.0       16
Name: dgestat, dtype: int64
1    82878
2    78615
Name: csex, dtype: int64
3430.0    2819
3402.0    2809
3317.0    2715
3487.0    2687
3515.0    2675
          ...
1258.0       1
803.0        1
4609.0       1
1982.0       1
4371.0       1
Name: dbrwt, Length: 3789, dtype: int64
1    157192
2      4086
3       203
4        12
Name: dplural, dtype: int64
9.0     67529
8.0     66879
7.0     12460
6.0      4441
5.0      2626
4.0      1856
10.0     1547
3.0      1303
2.0      1083
1.0      1047
0.0       154
Name: omaps, dtype: int64
9.0     123933
10.0     23332
8.0       9479
7.0       2010
6.0        791
1.0        416
5.0        366
4.0        235
3.0        148
2.0        129
0.0        127
Name: fmaps, dtype: int64
40.0    58932
39.0    31979
38.0    20971
41.0    19602
37.0     9973
42.0     5556
36.0     5103
35.0     2619
34.0     1622
33.0      969
32.0      804
31.0      483
30.0      408
29.0      289
28.0      253
43.0      246
27.0      215
26.0      197
25.0      167
24.0      163
22.0      112
23.0       97
20.0       84
21.0       77
18.0       39
19.0       39
44.0       32
17.0       25
Name: clingest, dtype: int64
2.0    159610
1.0      1800
Name: anemia, dtype: int64
2.0    160224
1.0      1186
Name: cardiac, dtype: int64
2.0    160074
1.0      1336
Name: lung, dtype: int64
2.0    157263
1.0      4147
Name: diabetes, dtype: int64
2.0    160372
1.0      1032
Name: herpes, dtype: int64
2.0    160102
1.0      1308
Name: chyper, dtype: int64
2.0    156481
1.0      4929
Name: phyper, dtype: int64
2.0    159234
1.0      2176
Name: pre4000, dtype: int64
2.0    158784
1.0      2626
Name: preterm, dtype: int64
2.0    129285
1.0     31977
Name: tobacco, dtype: int64
0    129285
2     12920
3      9269
1      6706
4      1330
5        59
Name: cigar6, dtype: int64
2.0    156129
1.0      5074
Name: alcohol, dtype: int64
0    156129
1       749
2       504
4       489
3       336
Name: drink5, dtype: int64
30.0    16204
25.0    10689
20.0     9178
40.0     8911
35.0     8401
        ...
92.0        3
95.0        2
91.0        2
94.0        2
97.0        1
Name: wgain, Length: 98, dtype: int64

In [63]:
indic_vars = ['rectype', 'pldel3', 'dmar', 'csex', 'anemia', 'cardiac', 'lung', 'diabetes', 'herpes',
       'chyper', 'phyper', 'pre4000', 'preterm', 'tobacco', 'alcohol']
for it in indic_vars:
    print(file[it].value_counts())
    file[it] = file[it].replace([1,2], [0,1])
    print(file[it].value_counts())

1    119821
2     41672
Name: rectype, dtype: int64
0    119821
1     41672
Name: rectype, dtype: int64
1    158285
2      3208
Name: pldel3, dtype: int64
0    158285
1      3208
Name: pldel3, dtype: int64
1    109600
2     51893
Name: dmar, dtype: int64
0    109600
1     51893
Name: dmar, dtype: int64
1    82878
2    78615
Name: csex, dtype: int64
0    82878
1    78615
Name: csex, dtype: int64
2.0    159610
1.0      1800
Name: anemia, dtype: int64
1.0    159610
0.0      1800
Name: anemia, dtype: int64
2.0    160224
1.0      1186
Name: cardiac, dtype: int64
1.0    160224
0.0      1186
Name: cardiac, dtype: int64
2.0    160074
1.0      1336
Name: lung, dtype: int64
1.0    160074
0.0      1336
Name: lung, dtype: int64
2.0    157263
1.0      4147
Name: diabetes, dtype: int64
1.0    157263
0.0      4147
Name: diabetes, dtype: int64
2.0    160372
1.0      1032
Name: herpes, dtype: int64
1.0    160372
0.0      1032
Name: herpes, dtype: int64
2.0    160102
1.0      1308
Name: chyper, dtype: int64
1.0    160102
0.0      1308
Name: chyper, dtype: int64
2.0    156481
1.0      4929
Name: phyper, dtype: int64
1.0    156481
0.0      4929
Name: phyper, dtype: int64
2.0    159234
1.0      2176
Name: pre4000, dtype: int64
1.0    159234
0.0      2176
Name: pre4000, dtype: int64
2.0    158784
1.0      2626
Name: preterm, dtype: int64
1.0    158784
0.0      2626
Name: preterm, dtype: int64
2.0    129285
1.0     31977
Name: tobacco, dtype: int64
1.0    129285
0.0     31977
Name: tobacco, dtype: int64
2.0    156129
1.0      5074
Name: alcohol, dtype: int64
1.0    156129
0.0      5074
Name: alcohol, dtype: int64

In [64]:
print(file['mrace3'].value_counts())

1    133608
3     24531
2      3354
Name: mrace3, dtype: int64

In [70]:
orfathdum = pd.get_dummies(file['orfath'], prefix = 'orfath')

In [71]:
ormothdum = pd.get_dummies(file['ormoth'], prefix = 'ormoth')

In [69]:
print(file.columns)

Index(['rectype', 'pldel3', 'birattnd', 'cntocpop', 'stresfip', 'dmage',
       'ormoth', 'mrace3', 'dmeduc', 'dmar', 'adequacy', 'nlbnl', 'dlivord',
       'totord9', 'monpre', 'nprevist', 'isllb10', 'dfage', 'orfath', 'dfeduc',
       'birmon', 'weekday', 'dgestat', 'csex', 'dbrwt', 'dplural', 'omaps',
       'fmaps', 'clingest', 'anemia', 'cardiac', 'lung', 'diabetes', 'herpes',
       'chyper', 'phyper', 'pre4000', 'preterm', 'tobacco', 'cigar6',
       'alcohol', 'drink5', 'wgain'],
      dtype='object')

In [88]:
data_clean = pd.concat([file, orfathdum, ormothdum], axis=1)
print(data_clean.shape)
print(data_clean.columns)

(161493, 55)
Index(['rectype', 'pldel3', 'birattnd', 'cntocpop', 'stresfip', 'dmage',
       'ormoth', 'mrace3', 'dmeduc', 'dmar', 'adequacy', 'nlbnl', 'dlivord',
       'totord9', 'monpre', 'nprevist', 'isllb10', 'dfage', 'orfath', 'dfeduc',
       'birmon', 'weekday', 'dgestat', 'csex', 'dbrwt', 'dplural', 'omaps',
       'fmaps', 'clingest', 'anemia', 'cardiac', 'lung', 'diabetes', 'herpes',
       'chyper', 'phyper', 'pre4000', 'preterm', 'tobacco', 'cigar6',
       'alcohol', 'drink5', 'wgain', 'orfath_0.0', 'orfath_1.0', 'orfath_2.0',
       'orfath_3.0', 'orfath_4.0', 'orfath_5.0', 'ormoth_0.0', 'ormoth_1.0',
       'ormoth_2.0', 'ormoth_3.0', 'ormoth_4.0', 'ormoth_5.0'],
      dtype='object')

In [75]:
for obj in data_clean.columns:
    print(data_clean[obj].value_counts())

0    119821
1     41672
Name: rectype, dtype: int64
0    158285
1      3208
Name: pldel3, dtype: int64
1.0    137000
2.0     16411
3.0      5950
4.0      1182
5.0       949
Name: birattnd, dtype: int64
0.0    50052
2.0    43136
3.0    30187
1.0    20666
Name: cntocpop, dtype: int64
42    157075
34      2277
36       739
39       417
24       358
10       289
54        99
12        40
0         28
51        27
6         23
37        18
13        11
17         8
25         8
21         7
47         7
45         7
9          6
48         6
26         5
53         5
55         4
4          3
8          3
40         3
27         2
29         2
11         2
19         2
23         1
22         1
46         1
32         1
44         1
33         1
41         1
28         1
38         1
1          1
31         1
30         1
Name: stresfip, dtype: int64
29    10307
28    10072
30     9910
27     9764
26     9251
31     9214
25     8834
32     8438
24     8025
22     7959
23     7760
33     7139
21     6937
20     6425
34     6042
19     5743
35     5207
18     4462
36     4075
17     3141
37     3003
38     2193
16     2080
39     1583
40     1082
15     1074
41      647
42      353
14      312
43      207
44       93
13       77
45       43
46       27
47        7
12        4
48        2
49        1
Name: dmage, dtype: int64
0.0    154987
2.0      4098
5.0       898
4.0       630
1.0       587
3.0        99
Name: ormoth, dtype: int64
1    133608
3     24531
2      3354
Name: mrace3, dtype: int64
12.0    66391
16.0    23744
14.0    15574
17.0    11411
13.0    11138
11.0     8692
10.0     7577
15.0     4706
9.0      4670
8.0      3600
7.0       425
6.0       255
5.0        97
0.0        88
4.0        77
3.0        50
2.0        44
1.0        31
Name: dmeduc, dtype: int64
0    109600
1     51893
Name: dmar, dtype: int64
1.0    111560
2.0     34658
3.0     11160
Name: adequacy, dtype: int64
0.0     64785
1.0     53842
2.0     26354
3.0      9751
4.0      3663
5.0      1535
6.0       737
7.0       390
8.0       187
9.0       105
10.0       61
11.0       28
12.0       22
13.0        2
14.0        1
15.0        1
Name: nlbnl, dtype: int64
1.0     64196
2.0     53279
3.0     26512
4.0     10165
5.0      3910
6.0      1660
7.0       818
8.0       416
9.0       229
10.0      121
11.0       65
12.0       40
13.0       24
14.0        6
15.0        1
16.0        1
Name: dlivord, dtype: int64
1.0    49137
2.0    47868
3.0    31074
4.0    16391
5.0     8234
6.0     4247
8.0     2444
7.0     2014
Name: totord9, dtype: int64
2.0    73216
3.0    33249
1.0    21713
4.0    11845
5.0     6833
6.0     4389
7.0     2920
0.0     2307
8.0     1758
9.0      572
Name: monpre, dtype: int64
12.0    26409
10.0    21525
13.0    15839
11.0    14211
14.0    13028
9.0     11474
8.0     10575
15.0     9229
7.0      6904
6.0      5441
5.0      3877
16.0     3722
4.0      2751
0.0      2307
3.0      2145
17.0     1633
2.0      1599
20.0     1578
18.0     1320
1.0      1048
19.0      574
21.0      224
22.0      221
25.0      208
24.0      116
23.0      109
30.0       84
26.0       43
28.0       33
27.0       29
29.0       15
35.0       13
32.0       13
49.0       13
31.0       12
36.0       12
40.0       10
34.0        8
38.0        7
33.0        7
39.0        3
48.0        2
47.0        1
46.0        1
41.0        1
37.0        1
42.0        1
Name: nprevist, dtype: int64
0.0    64196
5.0    22363
6.0    14940
9.0    13291
4.0    12639
3.0     9521
7.0     8765
8.0     5465
2.0     1447
1.0     1363
Name: isllb10, dtype: int64
29.0    9613
30.0    9482
31.0    9168
28.0    9056
32.0    9006
        ...
67.0       3
78.0       1
72.0       1
12.0       1
71.0       1
Name: dfage, Length: 62, dtype: int64
0.0    151361
2.0      4092
5.0       854
1.0       774
4.0       734
3.0       117
Name: orfath, dtype: int64
12.0    69610
16.0    22727
17.0    15196
14.0    12610
13.0     7248
11.0     6820
10.0     5394
15.0     3676
9.0      3019
8.0      3004
7.0       290
6.0       253
4.0       105
5.0        69
0.0        64
2.0        62
3.0        58
1.0        25
Name: dfeduc, dtype: int64
7     14191
8     14083
3     13981
9     13968
5     13928
4     13589
1     13417
6     13314
10    13308
12    12881
2     12422
11    12411
Name: birmon, dtype: int64
6    25518
3    25511
4    25370
5    25136
2    23163
7    19058
1    17737
Name: weekday, dtype: int64
40.0    36984
39.0    35953
41.0    22848
38.0    22181
37.0    10992
42.0     8270
36.0     5831
35.0     3480
43.0     3167
34.0     2266
44.0     1816
33.0     1279
45.0     1086
32.0      952
31.0      657
46.0      574
30.0      556
47.0      405
29.0      385
28.0      325
27.0      246
26.0      209
25.0      187
24.0      155
23.0      128
22.0      128
21.0       83
20.0       63
19.0       45
18.0       35
17.0       16
Name: dgestat, dtype: int64
0    82878
1    78615
Name: csex, dtype: int64
3430.0    2819
3402.0    2809
3317.0    2715
3487.0    2687
3515.0    2675
          ...
1258.0       1
803.0        1
4609.0       1
1982.0       1
4371.0       1
Name: dbrwt, Length: 3789, dtype: int64
1    157192
2      4086
3       203
4        12
Name: dplural, dtype: int64
9.0     67529
8.0     66879
7.0     12460
6.0      4441
5.0      2626
4.0      1856
10.0     1547
3.0      1303
2.0      1083
1.0      1047
0.0       154
Name: omaps, dtype: int64
9.0     123933
10.0     23332
8.0       9479
7.0       2010
6.0        791
1.0        416
5.0        366
4.0        235
3.0        148
2.0        129
0.0        127
Name: fmaps, dtype: int64
40.0    58932
39.0    31979
38.0    20971
41.0    19602
37.0     9973
42.0     5556
36.0     5103
35.0     2619
34.0     1622
33.0      969
32.0      804
31.0      483
30.0      408
29.0      289
28.0      253
43.0      246
27.0      215
26.0      197
25.0      167
24.0      163
22.0      112
23.0       97
20.0       84
21.0       77
18.0       39
19.0       39
44.0       32
17.0       25
Name: clingest, dtype: int64
1.0    159610
0.0      1800
Name: anemia, dtype: int64
1.0    160224
0.0      1186
Name: cardiac, dtype: int64
1.0    160074
0.0      1336
Name: lung, dtype: int64
1.0    157263
0.0      4147
Name: diabetes, dtype: int64
1.0    160372
0.0      1032
Name: herpes, dtype: int64
1.0    160102
0.0      1308
Name: chyper, dtype: int64
1.0    156481
0.0      4929
Name: phyper, dtype: int64
1.0    159234
0.0      2176
Name: pre4000, dtype: int64
1.0    158784
0.0      2626
Name: preterm, dtype: int64
1.0    129285
0.0     31977
Name: tobacco, dtype: int64
0    129285
2     12920
3      9269
1      6706
4      1330
5        59
Name: cigar6, dtype: int64
1.0    156129
0.0      5074
Name: alcohol, dtype: int64
0    156129
1       749
2       504
4       489
3       336
Name: drink5, dtype: int64
30.0    16204
25.0    10689
20.0     9178
40.0     8911
35.0     8401
        ...
92.0        3
95.0        2
91.0        2
94.0        2
97.0        1
Name: wgain, Length: 98, dtype: int64
1    151361
0     10132
Name: orfath_0.0, dtype: int64
0    160719
1       774
Name: orfath_1.0, dtype: int64
0    157401
1      4092
Name: orfath_2.0, dtype: int64
0    161376
1       117
Name: orfath_3.0, dtype: int64
0    160759
1       734
Name: orfath_4.0, dtype: int64
0    160639
1       854
Name: orfath_5.0, dtype: int64
1    154987
0      6506
Name: ormoth_0.0, dtype: int64
0    160906
1       587
Name: ormoth_1.0, dtype: int64
0    157395
1      4098
Name: ormoth_2.0, dtype: int64
0    161394
1        99
Name: ormoth_3.0, dtype: int64
0    160863
1       630
Name: ormoth_4.0, dtype: int64
0    160595
1       898
Name: ormoth_5.0, dtype: int64

In [96]:
data_clean_a = data_clean.dropna()
print(data_clean_a.columns)
print(data_clean_a.shape)

Index(['rectype', 'pldel3', 'birattnd', 'cntocpop', 'stresfip', 'dmage',
       'ormoth', 'mrace3', 'dmeduc', 'dmar', 'adequacy', 'nlbnl', 'dlivord',
       'totord9', 'monpre', 'nprevist', 'isllb10', 'dfage', 'orfath', 'dfeduc',
       'birmon', 'weekday', 'dgestat', 'csex', 'dbrwt', 'dplural', 'omaps',
       'fmaps', 'clingest', 'anemia', 'cardiac', 'lung', 'diabetes', 'herpes',
       'chyper', 'phyper', 'pre4000', 'preterm', 'tobacco', 'cigar6',
       'alcohol', 'drink5', 'wgain', 'orfath_0.0', 'orfath_1.0', 'orfath_2.0',
       'orfath_3.0', 'orfath_4.0', 'orfath_5.0', 'ormoth_0.0', 'ormoth_1.0',
       'ormoth_2.0', 'ormoth_3.0', 'ormoth_4.0', 'ormoth_5.0'],
      dtype='object')
(114610, 55)

In [94]:
data_clean_a.describe()

,rectype,pldel3,birattnd,cntocpop,stresfip,dmage,ormoth,mrace3,dmeduc,dmar,...,orfath_2.0,orfath_3.0,orfath_4.0,orfath_5.0,ormoth_0.0,ormoth_1.0,ormoth_2.0,ormoth_3.0,ormoth_4.0,ormoth_5.0
count,114610.000000,114610.000000,114610.000000,114610.000000,114610.000000,114610.000000,114610.000000,114610.000000,114610.000000,114610.000000,...,114610.000000,114610.000000,114610.000000,114610.000000,114610.000000,114610.000000,114610.000000,114610.000000,114610.000000,114610.000000
mean,0.262185,0.018096,1.201562,1.443033,41.742797,27.756662,0.090568,1.259148,13.210828,0.251139,...,0.024544,0.000681,0.004118,0.004659,0.964401,0.002906,0.023602,0.000707,0.003586,0.004799
std,0.439825,0.133300,0.564356,1.137175,2.166873,5.698714,0.522324,0.656755,2.272132,0.433670,...,0.154732,0.026079,0.064042,0.068100,0.185289,0.053825,0.151806,0.026575,0.059777,0.069108
min,0.000000,0.000000,1.000000,0.000000,0.000000,12.000000,0.000000,1.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,0.000000,0.000000,1.000000,0.000000,42.000000,24.000000,0.000000,1.000000,12.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,0.000000,0.000000,1.000000,2.000000,42.000000,28.000000,0.000000,1.000000,12.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000
75%,1.000000,0.000000,1.000000,2.000000,42.000000,32.000000,0.000000,1.000000,16.000000,1.000000,...,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000
max,1.000000,1.000000,5.000000,3.000000,55.000000,49.000000,5.000000,3.000000,17.000000,1.000000,...,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000

In [95]:
data_clean.describe()

,rectype,pldel3,birattnd,cntocpop,stresfip,dmage,ormoth,mrace3,dmeduc,dmar,...,orfath_2.0,orfath_3.0,orfath_4.0,orfath_5.0,ormoth_0.0,ormoth_1.0,ormoth_2.0,ormoth_3.0,ormoth_4.0,ormoth_5.0
count,161493.000000,161493.000000,161492.000000,144041.000000,161493.000000,161493.000000,161299.000000,161493.000000,158570.000000,161493.000000,...,161493.000000,161493.000000,161493.000000,161493.000000,161493.000000,161493.000000,161493.000000,161493.000000,161493.000000,161493.000000
mean,0.258042,0.019865,1.220773,1.371130,41.734614,27.272290,0.099753,1.324571,12.939282,0.321333,...,0.025339,0.000724,0.004545,0.005288,0.959713,0.003635,0.025376,0.000613,0.003901,0.005561
std,0.437559,0.139535,0.600129,1.160825,2.158817,5.844527,0.550013,0.723209,2.293448,0.466990,...,0.157152,0.026907,0.067264,0.072527,0.196631,0.060180,0.157264,0.024752,0.062337,0.074362
min,0.000000,0.000000,1.000000,0.000000,0.000000,12.000000,0.000000,1.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,0.000000,0.000000,1.000000,0.000000,42.000000,23.000000,0.000000,1.000000,12.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,0.000000,0.000000,1.000000,2.000000,42.000000,27.000000,0.000000,1.000000,12.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000
75%,1.000000,0.000000,1.000000,2.000000,42.000000,31.000000,0.000000,1.000000,15.000000,1.000000,...,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000
max,1.000000,1.000000,5.000000,3.000000,55.000000,49.000000,5.000000,3.000000,17.000000,1.000000,...,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000

In [110]:
cols = ['variable', 'no_null_mean', 'no_null_sd', 'all_mean', 'all_sd', 'diff', 'se_diff']
balance_t = pd.DataFrame(columns = cols)

for name in data_clean_a.columns:
    vals = []
    vals.append(name)
    vals.append(data_clean_a[name].mean())
    vals.append(data_clean_a[name].std())
    vals.append(data_clean[name].mean())
    vals.append(data_clean[name].std())
    vals.append(data_clean_a[name].mean()-data_clean[name].mean())
    vals.append(np.sqrt(((float(data_clean_a[name].std())**2)/float(data_clean_a[name].notnull().size)+((float(data_clean[name].std())**2)/float(data_clean_a[name].notnull().size)))))
    balance_t = balance_t.append(pd.DataFrame([vals], columns = cols), ignore_index = True)
print(balance_t)

      variable  no_null_mean  no_null_sd     all_mean      all_sd       diff  \
0      rectype      0.262185    0.439825     0.258042    0.437559   0.004143
1       pldel3      0.018096    0.133300     0.019865    0.139535  -0.001768
2     birattnd      1.201562    0.564356     1.220773    0.600129  -0.019211
3     cntocpop      1.443033    1.137175     1.371130    1.160825   0.071902
4     stresfip     41.742797    2.166873    41.734614    2.158817   0.008183
5        dmage     27.756662    5.698714    27.272290    5.844527   0.484371
6       ormoth      0.090568    0.522324     0.099753    0.550013  -0.009185
7       mrace3      1.259148    0.656755     1.324571    0.723209  -0.065423
8       dmeduc     13.210828    2.272132    12.939282    2.293448   0.271546
9         dmar      0.251139    0.433670     0.321333    0.466990  -0.070194
10    adequacy      1.297060    0.546108     1.362046    0.610569  -0.064986
11       nlbnl      0.966914    1.148117     1.046425    1.236149  -0.079511
12     dlivord      1.986240    1.174410     2.071363    1.269256  -0.085122
13     totord9      2.407006    1.457634     2.502717    1.545181  -0.095710
14      monpre      2.502225    1.326400     2.615981    1.478967  -0.113756
15    nprevist     11.152552    3.523881    10.787026    3.831803   0.365526
16     isllb10      3.321307    3.187841     3.308819    3.184766   0.012488
17       dfage     30.062455    6.410123    29.881010    6.529021   0.181445
18      orfath      0.094695    0.530573     0.104570    0.560197  -0.009875
19      dfeduc     13.276756    2.325483    13.099827    2.316007   0.176929
20      birmon      6.474479    3.394000     6.476875    3.407160  -0.002396
21     weekday      4.047029    1.881152     4.051383    1.888745  -0.004354
22     dgestat     39.152901    2.444981    39.028313    2.708495   0.124588
23        csex      0.485499    0.499792     0.486801    0.499827  -0.001303
24       dbrwt   3373.290760  585.174817  3335.836640  612.878055  37.454119
25     dplural      1.028104    0.174365     1.028038    0.173817   0.000066
26       omaps      8.117416    1.259542     8.077086    1.340189   0.040330
27       fmaps      9.009214    0.706982     8.991048    0.820058   0.018166
28    clingest     39.108821    2.056995    38.987421    2.324305   0.121401
29      anemia      0.990001    0.099495     0.988848    0.105012   0.001153
30     cardiac      0.993125    0.082633     0.992652    0.085404   0.000472
31        lung      0.992775    0.084690     0.991723    0.090601   0.001053
32    diabetes      0.973152    0.161639     0.974308    0.158216  -0.001155
33      herpes      0.993866    0.078079     0.993606    0.079706   0.000260
34      chyper      0.992287    0.087485     0.991896    0.089655   0.000390
35      phyper      0.969305    0.172492     0.969463    0.172060  -0.000158
36     pre4000      0.985516    0.119475     0.986519    0.115324  -0.001003
37     preterm      0.985865    0.118048     0.983731    0.126509   0.002134
38     tobacco      0.840625    0.366027     0.801708    0.398715   0.038917
39      cigar6      0.346218    0.860666     0.413414    0.927569  -0.067196
40     alcohol      0.990306    0.097979     0.968524    0.174600   0.021782
41      drink5      0.019955    0.230276     0.029841    0.291814  -0.009886
42       wgain     30.356435   11.884476    30.106394   12.174982   0.250041
43  orfath_0.0      0.962202    0.190708     0.937260    0.242495   0.024942
44  orfath_1.0      0.003795    0.061491     0.004793    0.069064  -0.000997
45  orfath_2.0      0.024544    0.154732     0.025339    0.157152  -0.000794
46  orfath_3.0      0.000681    0.026079     0.000724    0.026907  -0.000044
47  orfath_4.0      0.004118    0.064042     0.004545    0.067264  -0.000427
48  orfath_5.0      0.004659    0.068100     0.005288    0.072527  -0.000629
49  ormoth_0.0      0.964401    0.185289     0.959713    0.196631   0.004688
50  ormoth_1.0      0.002906    0.053825     0.003635    0.060180  -0.000729
51  ormoth_2.0      0.023602    0.151806     0.025376    0.157264  -0.001774
52  ormoth_3.0      0.000707    0.026575     0.000613    0.024752   0.000094
53  ormoth_4.0      0.003586    0.059777     0.003901    0.062337  -0.000315
54  ormoth_5.0      0.004799    0.069108     0.005561    0.074362  -0.000762

     se_diff
0   0.001833
1   0.000570
2   0.002433
3   0.004800
4   0.009035
5   0.024112
6   0.002241
7   0.002886
8   0.009536
9   0.001882
10  0.002420
11  0.004983
12  0.005108
13  0.006275
14  0.005868
15  0.015377
16  0.013310
17  0.027027
18  0.002279
19  0.009695
20  0.014206
21  0.007874
22  0.010778
23  0.002088
24  2.503029
25  0.000727
26  0.005433
27  0.003198
28  0.009168
29  0.000427
30  0.000351
31  0.000366
32  0.000668
33  0.000330
34  0.000370
35  0.000720
36  0.000490
37  0.000511
38  0.001599
39  0.003738
40  0.000591
41  0.001098
42  0.050256
43  0.000911
44  0.000273
45  0.000651
46  0.000111
47  0.000274
48  0.000294
49  0.000798
50  0.000238
51  0.000646
52  0.000107
53  0.000255
54  0.000300

In [106]:
data_clean['alcohol'].std()

0.1746004053936564

In [111]:
for name in data_clean_a.columns:
    print(name)

rectype
pldel3
birattnd
cntocpop
stresfip
dmage
ormoth
mrace3
dmeduc
dmar
adequacy
nlbnl
dlivord
totord9
monpre
nprevist
isllb10
dfage
orfath
dfeduc
birmon
weekday
dgestat
csex
dbrwt
dplural
omaps
fmaps
clingest
anemia
cardiac
lung
diabetes
herpes
chyper
phyper
pre4000
preterm
tobacco
cigar6
alcohol
drink5
wgain
orfath_0.0
orfath_1.0
orfath_2.0
orfath_3.0
orfath_4.0
orfath_5.0
ormoth_0.0
ormoth_1.0
ormoth_2.0
ormoth_3.0
ormoth_4.0
ormoth_5.0

In [ ]:
interesting_vars = ['pldel3', 'dmage', 'dmeduc', 'dmar', 'adequacy', 'dgestat', 'csex', 'dbrwt', 
                    'dplural', 'omaps', 'fmaps', 'alcohol', 'pre4000', 'preterm']